/* Synap desktop meeting capture: system/tab audio + microphone into the same local journal. */
(function(root){
'use strict';
const TARGET_RATE=16000,FRAME_SAMPLES=800,FRAME_BYTES=1600;
let session=null;
function supported(){return Boolean(root.navigator?.mediaDevices?.getDisplayMedia&&root.navigator?.mediaDevices?.getUserMedia&&root.AudioContext&&root.DKAudioStore)}
function downsample(input,inputRate,state){if(inputRate===TARGET_RATE)return Float32Array.from(input);const ratio=inputRate/TARGET_RATE,out=[];let pos=state.pos||0;while(pos<input.length){const i=Math.floor(pos),j=Math.min(input.length-1,i+1),f=pos-i;out.push(input[i]*(1-f)+input[j]*f);pos+=ratio}state.pos=pos-input.length;return Float32Array.from(out)}
function pcm16(samples){const out=new Uint8Array(samples.length*2),v=new DataView(out.buffer);for(let i=0;i<samples.length;i++){const x=Math.max(-1,Math.min(1,samples[i]));v.setInt16(i*2,x<0?x*32768:x*32767,true)}return out}
async function start(options={}){if(session)throw new Error('Desktop capture is already running.');if(!supported())throw new Error('Desktop meeting capture is not supported in this browser.');const display=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});let mic=null;try{mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})}catch(error){display.getTracks().forEach(t=>t.stop());throw error}const displayAudio=display.getAudioTracks();if(!displayAudio.length){display.getTracks().forEach(t=>t.stop());mic.getTracks().forEach(t=>t.stop());throw new Error('Share a tab/window with audio enabled. No meeting audio was provided.')}const journal=new root.DKAudioStore({onError:error=>console.warn('[synap desktop capture]',error)});await journal.open();const name=options.name||('Online meeting · '+new Date().toLocaleString([],{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}));const recordingId=await journal.begin(name,{deviceId:'desktop-browser',associationId:'desktop-browser',installationId:null});await journal.atomic(['recordings'],stores=>{const q=stores.recordings.get(recordingId);q.onsuccess=()=>{if(q.result)stores.recordings.put({...q.result,captureSource:'desktop-meeting',captureMode:'system+microphone',desktopCapture:true})}});const Ctx=root.AudioContext||root.webkitAudioContext,context=new Ctx({sampleRate:TARGET_RATE}),destination=context.createGain();destination.gain.value=0;destination.connect(context.destination);const processor=context.createScriptProcessor(4096,2,1),systemSource=context.createMediaStreamSource(new MediaStream(displayAudio)),micSource=context.createMediaStreamSource(mic),systemGain=context.createGain(),micGain=context.createGain();systemGain.gain.value=.7;micGain.gain.value=.65;systemSource.connect(systemGain).connect(processor);micSource.connect(micGain).connect(processor);processor.connect(destination);const pending=[],resample={pos:0};let sequence=0,stopping=false;processor.onaudioprocess=e=>{if(stopping)return;const channels=e.inputBuffer.numberOfChannels,a=e.inputBuffer.getChannelData(0),b=channels>1?e.inputBuffer.getChannelData(1):null,mix=new Float32Array(a.length);for(let i=0;i<a.length;i++)mix[i]=b?(a[i]+b[i])*.5:a[i];const samples=downsample(mix,context.sampleRate,resample);for(const x of samples)pending.push(x);while(pending.length>=FRAME_SAMPLES){const frame=pcm16(pending.splice(0,FRAME_SAMPLES));journal.append(recordingId,{sequence:sequence++,chunk:0,total:1,payload:frame})}};const state={recordingId,journal,context,processor,display,mic,sequence:()=>sequence,pending,stop:()=>stop('desktop-capture')};session=state;display.getTracks().forEach(track=>track.addEventListener('ended',()=>{if(session===state)stop('display-share-ended').catch(()=>{})},{once:true}));root.dispatchEvent?.(new CustomEvent('synap-desktop-capture-started',{detail:{recordingId}}));return{recordingId,name}}
async function stop(reason='desktop-capture'){const s=session;if(!s)return null;session=null;try{s.processor.onaudioprocess=null;if(s.pending.length){while(s.pending.length<FRAME_SAMPLES)s.pending.push(0);s.journal.append(s.recordingId,{sequence:s.sequence(),chunk:0,total:1,payload:pcm16(s.pending.splice(0,FRAME_SAMPLES))})}await s.journal.close(s.recordingId,reason);if(root.SynapProcessingPipeline?.refresh)Promise.resolve(root.SynapProcessingPipeline.refresh()).catch(()=>{});root.dispatchEvent?.(new CustomEvent('synap-memory-ready',{detail:{recordingId:s.recordingId,source:'desktop-meeting'}}));return s.recordingId}finally{try{s.display.getTracks().forEach(t=>t.stop())}catch(_){}try{s.mic.getTracks().forEach(t=>t.stop())}catch(_){}try{s.processor.disconnect()}catch(_){}try{await s.context.close()}catch(_){}}}
function state(){return session?{active:true,recordingId:session.recordingId}:{active:false,recordingId:null}}
function install(){if(!supported()||document.getElementById('synapDesktopCapture'))return;const capture=document.getElementById('capture');if(!capture)return;const box=document.createElement('div');box.id='synapDesktopCapture';box.className='desktop-capture-card';box.innerHTML='<div><strong>Online meeting</strong><small>Capture this computer’s meeting audio + your microphone. No bot joins the call.</small></div><button type="button" id="synapDesktopCaptureButton">Capture meeting</button>';const style=document.createElement('style');style.textContent='.desktop-capture-card{margin-top:12px;padding:11px 12px;border:1px solid var(--border,#d9e2ec);border-radius:14px;display:flex;gap:10px;align-items:center;justify-content:space-between;background:var(--surface,#fff)}.desktop-capture-card strong,.desktop-capture-card small{display:block}.desktop-capture-card small{margin-top:3px;font-size:10px;color:var(--muted,#64748b)}.desktop-capture-card button{border:0;border-radius:10px;padding:8px 11px;font:inherit;font-size:11px;font-weight:800;background:#102744;color:#fff;cursor:pointer}.desktop-capture-card button[data-active="true"]{background:#9f1d35}@media(max-width:560px){.desktop-capture-card{display:none}}';document.head.appendChild(style);capture.appendChild(box);const button=document.getElementById('synapDesktopCaptureButton');button.addEventListener('click',async()=>{button.disabled=true;try{if(session){await stop();button.textContent='Capture meeting';button.dataset.active='false'}else{await start();button.textContent='Stop meeting';button.dataset.active='true'}}catch(error){console.warn('[synap desktop capture]',error);root.dispatchEvent?.(new CustomEvent('synap-desktop-capture-error',{detail:{message:error.message}}))}finally{button.disabled=false}})}
root.SynapDesktopCapture={supported,start,stop,state,TARGET_RATE,FRAME_SAMPLES,FRAME_BYTES};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})(globalThis);
