/* Synap provenance links: one recording, one evidence chain. */
(function(root){
'use strict';
const DB='dk-pendant-recordings',STYLE_ID='synap-provenance-style';
let records=[],refreshing=false,initialized=false,lockTimer=0,sourceGeneration=0;
const $=(s,h=document)=>h.querySelector(s),$$=(s,h=document)=>[...h.querySelectorAll(s)];
function localDay(value){const d=new Date(value);if(Number.isNaN(d.getTime()))return'';return[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function clock(recording,offsetMs=0){const base=new Date(recording?.createdAt||recording?.startedAt||0).getTime();if(!Number.isFinite(base))return'';return new Date(base+Math.max(0,Number(offsetMs)||0)).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function meeting(r){return r?.meeting||{}}
function conversations(r){const m=meeting(r),list=Array.isArray(m.conversations)&&m.conversations.length?m.conversations:r?.conversations;return Array.isArray(list)?list:[]}
function textOf(value){if(typeof value==='string')return value.trim();if(value&&typeof value.text==='string')return value.text.trim();return''}
function sourceStart(value,fallback){const raw=value?.start_ms??value?.start_seconds;if(raw!=null&&Number.isFinite(Number(raw)))return value?.start_ms!=null?Number(raw):Number(raw)*1000;const other=fallback?.start_ms??fallback?.start_seconds;if(other!=null&&Number.isFinite(Number(other)))return fallback?.start_ms!=null?Number(other):Number(other)*1000;return 0}
function sourceEnd(value,fallback){const raw=value?.end_ms??value?.end_seconds;if(raw!=null&&Number.isFinite(Number(raw)))return value?.end_ms!=null?Number(raw):Number(raw)*1000;const other=fallback?.end_ms??fallback?.end_seconds;if(other!=null&&Number.isFinite(Number(other)))return fallback?.end_ms!=null?Number(other):Number(other)*1000;return sourceStart(value,fallback)}
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function loadRecords(){const db=await openDb();try{return await new Promise((res,rej)=>{const q=db.transaction('recordings').objectStore('recordings').getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}finally{db.close()}}
function injectStyle(){if($('#'+STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`.synap-provenance-summary{display:grid;gap:10px}.synap-provenance-summary>p{margin:0;white-space:pre-wrap}.synap-source-list{display:grid;gap:8px}.synap-source-link{width:100%;display:grid;grid-template-columns:68px minmax(0,1fr);gap:9px;text-align:left;border:1px solid var(--border,#d9e2ec);border-radius:12px;background:var(--surface,#fff);padding:9px 10px;color:inherit;cursor:pointer;font:inherit}.synap-source-link time{font-size:11px;font-weight:800;color:var(--muted,#64748b);font-variant-numeric:tabular-nums}.synap-source-link strong{display:block;font-size:12px}.synap-source-link span{display:block;margin-top:2px;font-size:11px;line-height:1.4;color:var(--muted,#64748b)}.synap-note-source{font-size:10px;color:var(--muted,#64748b);margin:0 0 6px}.synap-note-body{white-space:pre-wrap;margin:0;font-size:12px;line-height:1.5}.synap-provenance-transcript{display:grid;gap:7px;max-height:420px;overflow:auto}.synap-provenance-line{display:grid;grid-template-columns:52px 48px minmax(0,1fr);gap:7px;align-items:start;font-size:12px;line-height:1.45}.synap-provenance-line time{font-variant-numeric:tabular-nums;color:var(--muted,#64748b)}.synap-provenance-line b{font-size:11px}.synap-provenance-line p{margin:0}.recording-transcript[readonly]{cursor:text;background:transparent}.synap-transcript-integrity{display:block;margin:5px 0 0;font-size:10px;color:var(--muted,#64748b)}`;document.head.appendChild(s)}
function recordById(id){return records.find(r=>String(r.id)===String(id))||null}
function recordForInsight(card){const id=card?.dataset?.recordingId;if(id)return recordById(id);const stamp=$('time',card)?.dateTime;if(!stamp)return null;const target=new Date(stamp).getTime();return records.find(r=>new Date(r.createdAt).getTime()===target)||null}
function timestampToMs(value){const first=String(value||'').split(/[–-]/)[0].trim(),parts=first.split(':').map(Number);if(!parts.length||parts.some(x=>!Number.isFinite(x)))return null;if(parts.length===2)return(parts[0]*60+parts[1])*1000;if(parts.length===3)return(parts[0]*3600+parts[1]*60+parts[2])*1000;return null}
function transcriptPanel(recording){const host=document.createElement('div');host.className='synap-memory-panel synap-provenance-transcript';for(const line of String(recording.transcript||'').split(/\n+/).filter(x=>x.trim())){const match=line.match(/^\[([^\]]+)\]\s+([^:]+):\s*(.*)$/);if(!match){const p=document.createElement('p');p.className='synap-transcript-flat';p.textContent=line;host.appendChild(p);continue}const row=document.createElement('div');row.className='synap-provenance-line';const at=timestampToMs(match[1]);if(at!=null)row.dataset.startMs=String(at);const time=document.createElement('time');time.textContent=match[1];const speaker=document.createElement('b');speaker.textContent=/^(YOU|SELF|ME)$/i.test(match[2].trim())?'You':match[2].trim();const text=document.createElement('p');text.textContent=match[3];row.append(time,speaker,text);host.appendChild(row)}host.appendChild(root.SynapExperienceRecovery.createTranscriptNotice(recording));return host}
function summaryPanel(recording){const host=document.createElement('div');host.className='synap-memory-panel synap-provenance-summary';const lead=document.createElement('p');lead.textContent=meeting(recording).executive_summary||recording.summary||'';if(lead.textContent.trim())host.appendChild(lead);const list=document.createElement('div');list.className='synap-source-list';for(const c of conversations(recording)){const startMs=sourceStart(c),endMs=sourceEnd(c),button=document.createElement('button');button.type='button';button.className='synap-source-link';button.dataset.recordingId=recording.id;button.dataset.offsetMs=String(startMs);button.dataset.endMs=String(endMs);const time=document.createElement('time');time.textContent=clock(recording,startMs);const copy=document.createElement('div'),title=document.createElement('strong'),summary=document.createElement('span');title.textContent=c.title||'Conversation';summary.textContent=c.summary||'Open supporting transcript';copy.append(title,summary);button.append(time,copy);list.appendChild(button)}if(list.children.length)host.appendChild(list);return host}
function notesPanel(recording){const host=document.createElement('div');host.className='synap-memory-panel';const source=document.createElement('p');source.className='synap-note-source';source.textContent='Recording note · attached to '+clock(recording,0)+' · not used as transcript evidence';const note=document.createElement('p');note.className='synap-note-body';note.textContent=recording.notes||'';host.append(source,note);return host}
function buildMemoryView(recording){const host=document.createElement('div');host.className='synap-memory-view';host.dataset.synapProvenance='1';const tabs=document.createElement('div');tabs.className='synap-memory-tabs';tabs.setAttribute('role','tablist');const panels=[];function add(name,panel){const button=document.createElement('button');button.type='button';button.textContent=name;button.setAttribute('role','tab');button.dataset.synapView=name.toLowerCase();const entry={button,panel};panels.push(entry);button.addEventListener('click',()=>activate(entry));tabs.appendChild(button)}function activate(active){for(const entry of panels){const yes=entry===active;entry.button.setAttribute('aria-selected',String(yes));entry.panel.hidden=!yes}const card=host.closest('.insight-card');if(card)card.dataset.synapMemoryView=active.button.dataset.synapView}host.synapActivateView=name=>{const entry=panels.find(item=>item.button.dataset.synapView===name);if(entry)activate(entry)};if(recording.summary||meeting(recording).executive_summary||conversations(recording).length)add('Summary',summaryPanel(recording));if(String(recording.notes||'').trim())add('Notes',notesPanel(recording));add('Transcript',transcriptPanel(recording));if(!panels.length)return host;host.append(tabs,...panels.map(x=>x.panel));activate(panels[0]);return host}
function repairInsightBindings(){
  for(const card of $$('#insightsList .insight-card:not(.synap-merged-card)')){
    const recording=recordForInsight(card);if(!recording)continue;
    card.dataset.recordingId=recording.id;
    const signature=JSON.stringify([recording.id,recording.summary,recording.transcript,recording.notes,recording.meeting,recording.conversations]);
    if(card.synapProvenanceSignature===signature&&card.querySelector('[data-synap-provenance]'))continue;
    const active=card.querySelector('.synap-memory-tabs [aria-selected="true"]')?.dataset.synapView||card.dataset.synapMemoryView;
    $$('.synap-memory-view',card).forEach(n=>n.remove());
    const top=$('.insight-top',card),view=buildMemoryView(recording);
    if(view.childNodes.length&&top)top.insertAdjacentElement('afterend',view);
    if(active)view.synapActivateView(active);
    // The canonical tabs replace the source card's initial plain-text fallback.
    for(const selector of ['.insight-label','.insight-summary','.transcript-preview'])card.querySelector(selector)?.remove();
    card.synapProvenanceSignature=signature;
  }
}
function explicitOffset(button){for(const value of [button?.dataset?.offsetMs,button?.dataset?.sourceOffsetMs,button?.dataset?.startMs]){if(value!==undefined&&value!==null&&value!==''&&Number.isFinite(Number(value)))return Number(value)}return null}
function inferOffset(button,recording){const explicit=explicitOffset(button);if(explicit!=null)return Math.max(0,explicit);const strong=$('strong',button)?.textContent?.trim()||'';if(!strong)return 0;for(const c of conversations(recording)){if(String(c.title||'').trim()===strong)return sourceStart(c);for(const d of c.decisions||[])if(textOf(d)===strong)return sourceStart(d,c);for(const a of c.action_items||[])if(String(a.task||'').trim()===strong)return sourceStart(a,c);for(const f of c.follow_ups||[])if(textOf(f)===strong)return sourceStart(f,c)}return 0}
function repairTodayTimes(){for(const button of $$('.source-jump[data-id]')){const recording=recordById(button.dataset.id);if(!recording)continue;const offsetMs=inferOffset(button,recording);button.dataset.sourceOffsetMs=String(offsetMs);const ct=$('.conversation-time',button);if(ct)ct.textContent=clock(recording,offsetMs);const meta=$('small',button);if(meta&&button.classList.contains('brain-action-row')){const stamp=clock(recording,offsetMs);if(stamp&&!meta.textContent.startsWith(stamp))meta.textContent=stamp+(meta.textContent?' · '+meta.textContent:'')}}}
function nearestTranscriptPosition(text,targetMs){let best={index:0,delta:Infinity},match;const re=/^\[([^\]]+)\]/gm;while((match=re.exec(text))){const at=timestampToMs(match[1]);if(at==null)continue;const delta=Math.abs(at-targetMs);if(delta<best.delta)best={index:match.index,delta}}return best.index}
function seekAudio(audio,seconds){if(!audio)return;const apply=()=>{try{audio.currentTime=Math.max(0,seconds)}catch(_){}};if(audio.readyState>=1)apply();else audio.addEventListener('loadedmetadata',apply,{once:true})}
function hasStructuredMemory(recording){return Boolean(recording&&String(recording.transcript||'').trim()&&(String(recording.summary||'').trim()||meeting(recording).executive_summary||conversations(recording).length))}
function lockTranscript(card,recording){if(!card||!hasStructuredMemory(recording))return null;const textarea=$('.recording-transcript',card);if(!textarea)return null;textarea.readOnly=true;textarea.title='Transcript is generated source evidence. Corrections require a memory rebuild.';if(!card.querySelector('.synap-transcript-integrity')){const note=document.createElement('small');note.className='synap-transcript-integrity';note.textContent='Transcript is the evidence behind this summary; it is read-only to keep the memory linked.';textarea.insertAdjacentElement('afterend',note)}return textarea}
function lockProcessedLibraryTranscripts(){for(const card of $$('.recording-card[id^="recording-"]')){const id=String(card.id||'').replace(/^recording-/,''),recording=recordById(id);if(recording)lockTranscript(card,recording)}}
function scheduleLocks(){clearTimeout(lockTimer);lockTimer=setTimeout(lockProcessedLibraryTranscripts,20)}
function prepareTranscript(card,offsetMs){const details=$$('details',card).find(node=>$('summary',node)?.textContent?.trim()==='Transcript');if(details)details.open=true;const recording=recordById(String(card.id||'').replace(/^recording-/,'')),textarea=lockTranscript(card,recording)||$('.recording-transcript',card);if(!textarea)return false;const index=nearestTranscriptPosition(textarea.value,offsetMs);textarea.focus({preventScroll:true});textarea.setSelectionRange(index,index);const ratio=textarea.value.length?index/textarea.value.length:0;textarea.scrollTop=Math.max(0,ratio*(textarea.scrollHeight-textarea.clientHeight));return true}
function prepareAudio(card,offsetMs){const audio=$('audio',card);if(!audio)return false;if(!audio.getAttribute('src')){const load=$$('.recording-actions button',card).find(button=>button.textContent.trim()==='Load audio');if(load)load.click();let attempts=0;const wait=()=>{const current=document.getElementById(card.id),player=current&&$('audio',current);if(player?.getAttribute('src'))seekAudio(player,offsetMs/1000);else if(++attempts<45)setTimeout(wait,70)};wait()}else seekAudio(audio,offsetMs/1000);return true}
function revealLibraryCard(recordingId,offsetMs){let attempts=0;const find=()=>{const card=document.getElementById('recording-'+recordingId);if(!card){const more=$('#showMoreRecordingsButton');if(more&&!more.hidden)more.click();if(++attempts<75)return setTimeout(find,40);return}card.open=true;let contentAttempts=0;const ready=()=>{const current=document.getElementById('recording-'+recordingId);if(!current){if(++contentAttempts<75)return setTimeout(ready,40);return}const hasContent=Boolean($('.recording-content',current));if(!hasContent&&++contentAttempts<75)return setTimeout(ready,40);prepareTranscript(current,offsetMs);prepareAudio(current,offsetMs);current.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'})};setTimeout(ready,0)};find()}
async function hydrateRecording(recordingId){if(recordById(recordingId))return recordById(recordingId);const result=await root.SynapCloudHistory?.restoreRecording?.(recordingId,false);if(result?.error)throw result.error;records=await loadRecords();const recording=recordById(recordingId);if(!recording)throw new Error('This recording is not saved on this device. Sign in and retry.');return recording}
function navigate(recording,offsetMs){root.dispatchEvent?.(new CustomEvent('synap-library-source',{detail:{recordingId:recording.id}}));const picker=$('#datePicker'),d=localDay(recording.createdAt);if(picker&&picker.value!==d){picker.value=d;picker.dispatchEvent(new Event('change',{bubbles:true}))}if(root.SynapDashboardUI?.setView)root.SynapDashboardUI.setView('library',false);else location.hash='#library';setTimeout(()=>revealLibraryCard(recording.id,offsetMs),120)}
function sourceAccount(){try{return root.SynapAuth?.isSignedIn?.()?String(root.SynapAuth.session?.()?.profile?.uid||'signed-in'):''}catch(_){return ''}}
function sourceNotice(trigger,message,retry){
  if(!trigger?.isConnected)return;
  let notice=trigger.synapSourceNotice;
  if(!notice?.isConnected){notice=document.createElement('div');notice.className='synap-source-status';trigger.after(notice);trigger.synapSourceNotice=notice;}
  notice.replaceChildren();notice.hidden=!message;if(!message)return;
  const text=document.createElement('p');text.setAttribute('role','status');text.textContent=message;notice.append(text);
  if(retry){const button=document.createElement('button');button.type='button';button.textContent='Retry source';button.addEventListener('click',retry);notice.append(button);}
}
function openSource(recordingId,offsetMs=0,trigger){
  const id=String(recordingId||'');if(!id)return false;
  const offset=Math.max(0,Number(offsetMs)||0),local=recordById(id),generation=++sourceGeneration,account=sourceAccount();
  if(local){sourceNotice(trigger,'');navigate(local,offset);return true;}
  if(trigger){trigger.disabled=true;trigger.setAttribute('aria-busy','true');sourceNotice(trigger,'Opening source recording…');}
  let timer;
  const deadline=new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Opening the recording timed out. Please retry.')),20000)});
  Promise.race([hydrateRecording(id),deadline]).then(recording=>{
    if(generation!==sourceGeneration||account!==sourceAccount())return;
    sourceNotice(trigger,'');navigate(recording,offset);
  }).catch(error=>{
    if(generation!==sourceGeneration||account!==sourceAccount())return;
    sourceNotice(trigger,'Could not open source. '+(error.message||'Please retry.'),()=>openSource(id,offset,trigger));
  }).finally(()=>{clearTimeout(timer);if(trigger){trigger.disabled=false;trigger.removeAttribute('aria-busy');}});
  return true;
}
function bindClicks(){document.addEventListener('click',event=>{const own=event.target.closest?.('.synap-source-link');if(own){event.preventDefault();event.stopImmediatePropagation();openSource(own.dataset.recordingId,explicitOffset(own)||0,own);return}const legacy=event.target.closest?.('.source-jump[data-id]');if(!legacy)return;const recording=recordById(legacy.dataset.id);event.preventDefault();event.stopImmediatePropagation();openSource(legacy.dataset.id,recording?inferOffset(legacy,recording):(explicitOffset(legacy)||0),legacy)},true)}
async function refresh(){if(refreshing)return;refreshing=true;try{records=await loadRecords().catch(()=>[]);repairInsightBindings();repairTodayTimes();lockProcessedLibraryTranscripts()}finally{refreshing=false}}
function init(){if(initialized)return;initialized=true;injectStyle();bindClicks();let refreshTimer=0;const schedule=()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,60)};['synap-insights-rendered','synap-memory-ready','synap-cloud-history-updated','synap-transcript-updated','synap-follow-up-updated'].forEach(name=>root.addEventListener(name,schedule));$('#datePicker')?.addEventListener('change',schedule);const library=$('#recordingsList');if(library&&root.MutationObserver)new root.MutationObserver(scheduleLocks).observe(library,{childList:true,subtree:true});document.addEventListener('toggle',event=>{if(event.target?.classList?.contains('recording-card')&&event.target.open)scheduleLocks()},true);refresh();setTimeout(refresh,250)}
root.SynapProvenance=Object.freeze({refresh,buildMemoryView,openSource,inferOffset,timestampToMs,explicitOffset,revealLibraryCard,lockProcessedLibraryTranscripts,hasStructuredMemory});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(globalThis);
