/* Synap Voice Profile: explicit, privacy-safe enrollment for owner speech. */
(function(root){'use strict';
const STYLE_ID='synapVoiceProfileStyle',RECORD_SECONDS=10,TARGET_RATE=16000;
let status=null,busy=false,dialog=null,recordingCleanup=null;
const $=s=>document.querySelector(s);
function signedIn(){try{return Boolean(root.SynapAuth?.isSignedIn?.())}catch(_){return false}}
function providerIsSynap(){try{return String(JSON.parse(localStorage.getItem('synap-ai-provider-settings')||'{}').provider||'synap')==='synap'}catch(_){return true}}
async function request(path,options){if(!root.SynapAuth?.authedFetch)throw new Error('Synap account is unavailable.');const response=await root.SynapAuth.authedFetch(path,options||{});let data=null;try{data=await response.json()}catch(_){}if(!response.ok){const e=new Error(data?.error?.message||('HTTP '+response.status));e.status=response.status;throw e}return data}
function style(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.synap-voice-profile{display:flex;align-items:center;gap:12px;margin-top:12px;padding:12px;border:1px solid var(--border,#dbe3ec);border-radius:14px;background:rgba(127,145,165,.05)}.synap-voice-profile-copy{min-width:0;flex:1;display:grid;gap:3px}.synap-voice-profile-copy strong{font-size:13px}.synap-voice-profile-copy span{font-size:11px;line-height:1.35;color:var(--muted,#64748b)}.synap-voice-profile-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.synap-voice-profile-actions button{border:0;border-radius:10px;padding:8px 10px;font:inherit;font-size:11px;font-weight:750;cursor:pointer}.synap-voice-primary{background:#102744;color:#fff}.synap-voice-secondary{background:rgba(127,145,165,.12);color:inherit}.synap-voice-profile-actions button:disabled{opacity:.45;cursor:not-allowed}.synap-voice-dialog{border:0;border-radius:22px;padding:0;width:min(440px,calc(100vw - 28px));max-width:440px;background:var(--surface,#fff);color:inherit;box-shadow:0 24px 80px rgba(15,23,42,.28)}.synap-voice-dialog::backdrop{background:rgba(15,23,42,.48);backdrop-filter:blur(2px)}.synap-voice-dialog-body{padding:22px;display:grid;gap:16px}.synap-voice-dialog h3{margin:0;font-size:20px}.synap-voice-dialog p{margin:0;color:var(--muted,#64748b);font-size:13px;line-height:1.5}.synap-voice-consent{display:flex;align-items:flex-start;gap:9px;font-size:12px;line-height:1.4}.synap-voice-consent input{margin-top:2px}.synap-voice-progress{display:grid;place-items:center;min-height:84px;border-radius:16px;background:rgba(127,145,165,.08);text-align:center}.synap-voice-progress strong{font-size:26px}.synap-voice-dialog-actions{display:flex;gap:8px;justify-content:flex-end}.synap-voice-dialog-actions button{border:0;border-radius:11px;padding:10px 14px;font:inherit;font-weight:750;cursor:pointer}.synap-voice-error{color:#a64040!important}.synap-voice-ready{color:#237a57!important}@media(max-width:560px){.synap-voice-profile{align-items:flex-start;flex-direction:column}.synap-voice-profile-actions{width:100%;justify-content:flex-start}.synap-voice-dialog-actions{justify-content:stretch}.synap-voice-dialog-actions button{flex:1}}
`;document.head.appendChild(s)}
function row(){let host=$('#synapVoiceProfile');if(host)return host;const parent=$('#synapAccountFields');if(!parent)return null;host=document.createElement('div');host.id='synapVoiceProfile';host.className='synap-voice-profile';host.hidden=true;const copy=document.createElement('div');copy.className='synap-voice-profile-copy';const title=document.createElement('strong');title.textContent='Voice profile';const detail=document.createElement('span');detail.id='synapVoiceProfileStatus';detail.textContent='Checking availability…';copy.append(title,detail);const actions=document.createElement('div');actions.className='synap-voice-profile-actions';const setup=document.createElement('button');setup.type='button';setup.id='synapVoiceProfileSetup';setup.className='synap-voice-primary';setup.textContent='Set up';setup.addEventListener('click',openEnrollment);const remove=document.createElement('button');remove.type='button';remove.id='synapVoiceProfileDelete';remove.className='synap-voice-secondary';remove.textContent='Delete';remove.hidden=true;remove.addEventListener('click',deleteProfile);actions.append(setup,remove);host.append(copy,actions);const connection=$('#synapConnectionDetails');if(connection)connection.before(host);else parent.appendChild(host);return host}
function render(){const host=row();if(!host)return;const detail=$('#synapVoiceProfileStatus'),setup=$('#synapVoiceProfileSetup'),remove=$('#synapVoiceProfileDelete');const visible=signedIn()&&providerIsSynap();host.hidden=!visible;if(!visible)return;if(!status){detail.textContent='Checking availability…';setup.disabled=true;remove.hidden=true;return}if(!status.available){detail.textContent='Voice profiling will appear after the speaker service is deployed.';setup.disabled=true;remove.hidden=true;return}setup.disabled=busy;remove.disabled=busy;if(status.enrolled){detail.textContent='Ready · your speech can be tagged as You.';detail.classList.add('synap-voice-ready');setup.textContent='Re-record';remove.hidden=false}else{detail.classList.remove('synap-voice-ready');detail.textContent='Not set up · record about 10 seconds once.';setup.textContent='Set up';remove.hidden=true}}
function makeDialog(){if(dialog)return dialog;dialog=document.createElement('dialog');dialog.className='synap-voice-dialog';dialog.id='synapVoiceProfileDialog';const body=document.createElement('div');body.className='synap-voice-dialog-body';const h=document.createElement('h3');h.textContent='Create your voice profile';const intro=document.createElement('p');intro.textContent='Speak naturally for about 10 seconds in a quiet place. Synap turns this sample into an encrypted voice fingerprint so your transcript can label your words as “You”. The enrollment audio is not saved.';const consent=document.createElement('label');consent.className='synap-voice-consent';const check=document.createElement('input');check.type='checkbox';check.id='synapVoiceConsent';const text=document.createElement('span');text.textContent='I agree to create an encrypted voice profile for identifying my own speech in Synap memories.';consent.append(check,text);const progress=document.createElement('div');progress.className='synap-voice-progress';const progressText=document.createElement('div');const big=document.createElement('strong');big.id='synapVoiceCountdown';big.textContent='10s';const small=document.createElement('p');small.id='synapVoicePrompt';small.textContent='When ready, start and speak in your normal voice.';progressText.append(big,small);progress.appendChild(progressText);const error=document.createElement('p');error.id='synapVoiceError';error.className='synap-voice-error';error.hidden=true;const actions=document.createElement('div');actions.className='synap-voice-dialog-actions';const cancel=document.createElement('button');cancel.type='button';cancel.className='synap-voice-secondary';cancel.textContent='Cancel';cancel.addEventListener('click',closeDialog);const start=document.createElement('button');start.type='button';start.id='synapVoiceStart';start.className='synap-voice-primary';start.textContent='Start recording';start.disabled=true;start.addEventListener('click',enroll);check.addEventListener('change',()=>{start.disabled=!check.checked||busy});actions.append(cancel,start);body.append(h,intro,consent,progress,error,actions);dialog.appendChild(body);document.body.appendChild(dialog);return dialog}
function openEnrollment(){if(busy||!status?.available)return;if(String(document.body?.dataset?.state||'')==='recording'){const detail=$('#synapVoiceProfileStatus');if(detail)detail.textContent='Stop pendant listening before voice-profile setup.';return}const d=makeDialog();const check=$('#synapVoiceConsent'),start=$('#synapVoiceStart'),error=$('#synapVoiceError'),count=$('#synapVoiceCountdown'),prompt=$('#synapVoicePrompt');check.checked=false;start.disabled=true;error.hidden=true;count.textContent=RECORD_SECONDS+'s';prompt.textContent='When ready, start and speak in your normal voice.';if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','')}
function closeDialog(){if(recordingCleanup)recordingCleanup();if(!dialog)return;if(typeof dialog.close==='function'&&dialog.open)dialog.close();else dialog.removeAttribute('open')}
function concatFloat32(chunks){const length=chunks.reduce((n,x)=>n+x.length,0),out=new Float32Array(length);let offset=0;chunks.forEach(x=>{out.set(x,offset);offset+=x.length});return out}
function resample(input,sourceRate,targetRate){if(sourceRate===targetRate)return input;const ratio=sourceRate/targetRate,length=Math.max(1,Math.floor(input.length/ratio)),out=new Float32Array(length);for(let i=0;i<length;i+=1){const start=Math.floor(i*ratio),end=Math.max(start+1,Math.min(input.length,Math.floor((i+1)*ratio)));let sum=0;for(let j=start;j<end;j+=1)sum+=input[j];out[i]=sum/(end-start)}return out}
function wav16(samples,rate){const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);function ascii(offset,text){for(let i=0;i<text.length;i+=1)view.setUint8(offset+i,text.charCodeAt(i))}ascii(0,'RIFF');view.setUint32(4,36+samples.length*2,true);ascii(8,'WAVE');ascii(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);ascii(36,'data');view.setUint32(40,samples.length*2,true);let o=44;for(let i=0;i<samples.length;i+=1){const x=Math.max(-1,Math.min(1,samples[i]));view.setInt16(o,x<0?x*32768:x*32767,true);o+=2}return buffer}
async function capture(seconds,onTick){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone access is unavailable in this browser.');const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});const AudioContext=root.AudioContext||root.webkitAudioContext;if(!AudioContext){stream.getTracks().forEach(t=>t.stop());throw new Error('Audio capture is unavailable in this browser.')}const context=new AudioContext(),source=context.createMediaStreamSource(stream),processor=context.createScriptProcessor(4096,1,1),chunks=[];let finished=false,timer=0,interval=0;const cleanup=()=>{if(finished)return;finished=true;clearTimeout(timer);clearInterval(interval);try{processor.disconnect()}catch(_){}try{source.disconnect()}catch(_){}stream.getTracks().forEach(t=>t.stop());context.close().catch(()=>{});recordingCleanup=null};recordingCleanup=cleanup;processor.onaudioprocess=e=>{if(!finished)chunks.push(new Float32Array(e.inputBuffer.getChannelData(0)))};source.connect(processor);processor.connect(context.destination);await context.resume();const started=Date.now();onTick(seconds);interval=setInterval(()=>onTick(Math.max(0,Math.ceil(seconds-(Date.now()-started)/1000))),250);await new Promise(resolve=>{timer=setTimeout(resolve,seconds*1000)});const sourceRate=context.sampleRate;cleanup();const samples=resample(concatFloat32(chunks),sourceRate,TARGET_RATE);if(samples.length<TARGET_RATE*5)throw new Error('The recording was too short. Please try again.');return wav16(samples,TARGET_RATE)}
async function enroll(){if(busy)return;busy=true;render();const start=$('#synapVoiceStart'),check=$('#synapVoiceConsent'),error=$('#synapVoiceError'),count=$('#synapVoiceCountdown'),prompt=$('#synapVoicePrompt');start.disabled=true;check.disabled=true;error.hidden=true;try{prompt.textContent='Speak naturally…';const audio=await capture(RECORD_SECONDS,remaining=>{count.textContent=remaining+'s'});count.textContent='✓';prompt.textContent='Creating encrypted voice profile…';status=await request('/v1/voice-profile',{method:'POST',headers:{'Content-Type':'audio/wav'},body:audio});prompt.textContent='Voice profile ready.';setTimeout(()=>closeDialog(),650)}catch(e){error.textContent=e.message||'Could not create voice profile.';error.hidden=false;count.textContent=RECORD_SECONDS+'s';prompt.textContent='Try again in a quiet place.'}finally{busy=false;check.disabled=false;start.disabled=!check.checked;render()}}
async function deleteProfile(){if(busy||!status?.enrolled)return;if(!root.confirm('Delete your voice profile? Future memories will stop identifying your speech as You.'))return;busy=true;render();try{await request('/v1/voice-profile',{method:'DELETE'});status={...status,enrolled:false,model:null,createdAt:null,updatedAt:null};render()}catch(e){const detail=$('#synapVoiceProfileStatus');if(detail)detail.textContent=e.message||'Could not delete voice profile.'}finally{busy=false;render()}}
async function refresh(){style();row();if(!signedIn()||!providerIsSynap()){status=null;render();return}try{status=await request('/v1/voice-profile')}catch(e){if(e?.status===404){status={available:false,enrolled:false}}else{status={available:false,enrolled:false};console.warn('[synap voice] status failed',e)}}render()}
function bind(){style();row();if(root.SynapAuth?.onChange)root.SynapAuth.onChange(()=>setTimeout(refresh,0));$('#providerInput')?.addEventListener('change',()=>setTimeout(refresh,0));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh()});refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
root.SynapVoiceProfile={refresh,get status(){return status}};
})(globalThis);
