'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const index=fs.readFileSync('index.html','utf8');
const brain=fs.readFileSync('brain-ui.js','utf8');
assert(index.includes('href="brain.css?v=1.0.0-brain2"'),'brain.css must be linked by the document, not merely cached');
assert(index.includes('id="actionableMemory"'),'Actions must exist in the base Today HTML');
for(const id of ['decisionCount','commitmentCount','waitingCount','decisionList','commitmentList','waitingList'])assert(index.includes('id="'+id+'"'),'missing static Actions node '+id);
assert(!/function install\(\)\{\s*if\(\$\('#actionableMemory'\)\)return/.test(brain),'brain-ui must not abort installation when static Actions exists');
assert(brain.includes("if(brief&&glance&&!$('#actionableMemory'))"),'brain-ui should keep dynamic Actions only as a fallback');
console.log('PASS: Actions is a static visible Today surface and brain-ui enhances it without aborting.');
