'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const profiles=require('../devices/profiles.js');
const caps=require('../devices/capabilities.js');
const c3=profiles.BY_MODULE[2];
const info={...c3,supported:1|4|8|16|32|64,ready:1|4|8|16|32|64,mediaVersion:1,legacy:false};
assert.equal(caps.hasMedia(info),true,'C3 media-v1 must be recognized');
assert.equal(caps.ready(info,'sd'),true,'C3 mounted SD must be ready');
assert(c3.features.includes('sd'));
assert.equal(c3.protocols.media,1);
const transfer=fs.readFileSync(path.join(root,'devices/chakshu/transfer.js'),'utf8');
const media=fs.readFileSync(path.join(root,'devices/chakshu/media.js'),'utf8');
const preview=fs.readFileSync(path.join(root,'devices/chakshu/capture-preview.js'),'utf8');
const library=fs.readFileSync(path.join(root,'devices/chakshu/library.js'),'utf8');
assert(transfer.includes('{0,51}\\.wav'));
assert.match(media,/Odyssey SD audio/);
assert.match(media,/schedulePendingSync\(250\)/);
assert.match(media,/camera\(\)\.request\(14/);
assert.match(preview,/id = 'deviceSDSettings'/);
assert.match(preview,/Clear SD Card/);
assert.match(preview,/await verifyAudio\(record\.id, source\.main\)/);
const verified=preview.indexOf('await verifyAudio(record.id, source.main)');
assert(verified>=0);
assert(preview.indexOf('await deleteSyncedSet(path)',verified)>verified);
assert.match(library,/Not synced · On device SD/);
assert.match(library,/Syncing from device SD/);
console.log('PASS: Odyssey C3 SD files surface in Memories, sync uses verified delete, and Settings exposes safe clear.');
